Repository Dhauzur/front-sochamar, pull requests merged in 2020-02, with the labels that each got.

#14 Set max passanger per service ok
  CHANGELOG.rst
  src/App.vue
  src/components/ErrorMessage.vue
  src/store/modules/Lodging.js
  src/views/Home.vue
  src/views/Lodging.vue
Labels: Restriction

#20 token problem on f5 or window close fixed, control of isLogged state …
  src/App.vue
  src/store/modules/auth.js
Labels: bug

#19 Maurocrudcompanies
  CHANGELOG.rst
  src/App.vue
  src/components/UserBar.vue
  src/components/passengers/ListPassengers.vue
  src/components/passengers/PassengersDialog.vue
  src/components/passengers/PassengersForm.vue
  src/router/index.js
  src/store/index.js
  src/store/modules/Company.js
  src/store/modules/Entity.js
  src/store/modules/Lodging.js
  src/store/modules/Maintenance.js
  src/store/modules/Room.js
  src/store/modules/auth.js
  src/views/Company.vue
  src/views/Entity.vue
  src/views/Group.vue
  src/views/Lodging.vue
  src/views/Login.vue
  src/views/Register.vue
  src/views/Room.vue
Labels: New feature
